# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Medical Toolkit
email: bdbaruah@orthodoc.in
description: >
  A Doctor's Ultimate Survival Guide in the Digital Space
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://themedicaltoolkit.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Biswajit Baruah'
bio: >
  Hip Replacement Surgeon from Chennai.
  Developer of Diagnox mobile app.
  Wannabe long distance runner.
author_image: "/assets/images/author.jpg"
twitter_username: 0rthodoc
github_username:  orthodoc

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - emoji_for_jekyll
  - jekyll-compose
  # - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

collections:
  courses:
    output: true
    permalink: /courses/:path/
    title: Courses

include: ["_pages"]

# seo options
twitter:
  username: 0rthodoc
facebook:
  publisher: medtoolkit
social:
  name: Biswajit D Baruah
  links:
    - https://twitter.com/0rthodoc
    - https://www.facebook.com/medtoolkit
    - https://www.linkedin.com/bdbaruah
    - https://github.com/orthodoc
    - https://plus.google.com/bdbaruah
